# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'scala-controlXWatwy.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1486, 848)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 1461, 71))
        font = QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QRect(390, 90, 531, 691))
        font1 = QFont()
        font1.setPointSize(14)
        self.groupBox.setFont(font1)
        self.progressBar = QProgressBar(self.groupBox)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(100, 50, 421, 41))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setPointSize(14)
        font2.setStrikeOut(False)
        font2.setKerning(True)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.progressBar.setFont(font2)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setMaximum(200)
        self.progressBar.setValue(24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(Qt.Horizontal)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 91, 91))
        font3 = QFont()
        font3.setPointSize(40)
        font3.setBold(False)
        font3.setWeight(50)
        self.label_2.setFont(font3)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.horizontalLayoutWidget = QWidget(self.groupBox)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(100, 90, 351, 51))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.j1_minus = QPushButton(self.horizontalLayoutWidget)
        self.j1_minus.setObjectName(u"j1_minus")
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(True)
        font4.setWeight(75)
        self.j1_minus.setFont(font4)

        self.horizontalLayout.addWidget(self.j1_minus)

        self.j1_plus = QPushButton(self.horizontalLayoutWidget)
        self.j1_plus.setObjectName(u"j1_plus")
        self.j1_plus.setFont(font4)

        self.horizontalLayout.addWidget(self.j1_plus)

        self.horizontalLayoutWidget_2 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(100, 230, 351, 51))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.j2_minus = QPushButton(self.horizontalLayoutWidget_2)
        self.j2_minus.setObjectName(u"j2_minus")
        self.j2_minus.setFont(font4)

        self.horizontalLayout_2.addWidget(self.j2_minus)

        self.j2_plus = QPushButton(self.horizontalLayoutWidget_2)
        self.j2_plus.setObjectName(u"j2_plus")
        self.j2_plus.setFont(font4)

        self.horizontalLayout_2.addWidget(self.j2_plus)

        self.progressBar_2 = QProgressBar(self.groupBox)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(100, 190, 420, 41))
        self.progressBar_2.setMaximum(200)
        self.progressBar_2.setValue(24)
        self.progressBar_2.setTextVisible(True)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 190, 91, 91))
        self.label_3.setFont(font3)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.horizontalLayoutWidget_3 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(100, 370, 351, 51))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.j3_minus = QPushButton(self.horizontalLayoutWidget_3)
        self.j3_minus.setObjectName(u"j3_minus")
        self.j3_minus.setFont(font4)

        self.horizontalLayout_3.addWidget(self.j3_minus)

        self.j3_plus = QPushButton(self.horizontalLayoutWidget_3)
        self.j3_plus.setObjectName(u"j3_plus")
        self.j3_plus.setFont(font4)

        self.horizontalLayout_3.addWidget(self.j3_plus)

        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 330, 91, 91))
        self.label_4.setFont(font3)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.progressBar_3 = QProgressBar(self.groupBox)
        self.progressBar_3.setObjectName(u"progressBar_3")
        self.progressBar_3.setGeometry(QRect(100, 330, 420, 41))
        self.progressBar_3.setMaximum(200)
        self.progressBar_3.setValue(24)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_4 = QProgressBar(self.groupBox)
        self.progressBar_4.setObjectName(u"progressBar_4")
        self.progressBar_4.setGeometry(QRect(100, 470, 420, 41))
        self.progressBar_4.setMaximum(200)
        self.progressBar_4.setValue(24)
        self.progressBar_4.setTextVisible(True)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 470, 91, 91))
        self.label_5.setFont(font3)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.horizontalLayoutWidget_4 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(100, 510, 351, 51))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.z_minus = QPushButton(self.horizontalLayoutWidget_4)
        self.z_minus.setObjectName(u"z_minus")
        self.z_minus.setFont(font4)

        self.horizontalLayout_4.addWidget(self.z_minus)

        self.z_plus = QPushButton(self.horizontalLayoutWidget_4)
        self.z_plus.setObjectName(u"z_plus")
        self.z_plus.setFont(font4)

        self.horizontalLayout_4.addWidget(self.z_plus)

        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 590, 91, 91))
        font5 = QFont()
        font5.setPointSize(20)
        font5.setBold(False)
        font5.setWeight(50)
        self.label_6.setFont(font5)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.horizontalLayoutWidget_5 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(100, 630, 351, 51))
        font6 = QFont()
        font6.setPointSize(20)
        self.horizontalLayoutWidget_5.setFont(font6)
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.step_minus = QPushButton(self.horizontalLayoutWidget_5)
        self.step_minus.setObjectName(u"step_minus")
        self.step_minus.setFont(font4)

        self.horizontalLayout_5.addWidget(self.step_minus)

        self.step_plus = QPushButton(self.horizontalLayoutWidget_5)
        self.step_plus.setObjectName(u"step_plus")
        self.step_plus.setFont(font4)

        self.horizontalLayout_5.addWidget(self.step_plus)

        self.plainTextEdit_4 = QPlainTextEdit(self.groupBox)
        self.plainTextEdit_4.setObjectName(u"plainTextEdit_4")
        self.plainTextEdit_4.setGeometry(QRect(100, 580, 351, 51))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(940, 90, 531, 171))
        self.groupBox_2.setFont(font1)
        self.groupBox_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.groupBox_2.setCheckable(False)
        self.horizontalLayoutWidget_6 = QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_6.setObjectName(u"horizontalLayoutWidget_6")
        self.horizontalLayoutWidget_6.setGeometry(QRect(10, 40, 511, 61))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.horizontalLayoutWidget_6)
        self.label_7.setObjectName(u"label_7")

        self.horizontalLayout_6.addWidget(self.label_7)

        self.ik_pos_x = QPlainTextEdit(self.horizontalLayoutWidget_6)
        self.ik_pos_x.setObjectName(u"ik_pos_x")
        font7 = QFont()
        font7.setPointSize(22)
        self.ik_pos_x.setFont(font7)
        self.ik_pos_x.setLayoutDirection(Qt.LeftToRight)
        self.ik_pos_x.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ik_pos_x.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ik_pos_x.setReadOnly(False)

        self.horizontalLayout_6.addWidget(self.ik_pos_x)

        self.label_8 = QLabel(self.horizontalLayoutWidget_6)
        self.label_8.setObjectName(u"label_8")

        self.horizontalLayout_6.addWidget(self.label_8)

        self.ik_pos_y = QPlainTextEdit(self.horizontalLayoutWidget_6)
        self.ik_pos_y.setObjectName(u"ik_pos_y")
        self.ik_pos_y.setFont(font7)
        self.ik_pos_y.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ik_pos_y.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

        self.horizontalLayout_6.addWidget(self.ik_pos_y)

        self.label_9 = QLabel(self.horizontalLayoutWidget_6)
        self.label_9.setObjectName(u"label_9")

        self.horizontalLayout_6.addWidget(self.label_9)

        self.ik_pos_z = QPlainTextEdit(self.horizontalLayoutWidget_6)
        self.ik_pos_z.setObjectName(u"ik_pos_z")
        self.ik_pos_z.setFont(font7)
        self.ik_pos_z.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ik_pos_z.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

        self.horizontalLayout_6.addWidget(self.ik_pos_z)

        self.move_position = QPushButton(self.groupBox_2)
        self.move_position.setObjectName(u"move_position")
        self.move_position.setGeometry(QRect(10, 110, 511, 51))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 90, 361, 161))
        self.groupBox_3.setFont(font1)
        self.com_select = QComboBox(self.groupBox_3)
        self.com_select.setObjectName(u"com_select")
        self.com_select.setGeometry(QRect(20, 40, 181, 34))
        self.baudrate_text = QPlainTextEdit(self.groupBox_3)
        self.baudrate_text.setObjectName(u"baudrate_text")
        self.baudrate_text.setGeometry(QRect(20, 90, 181, 41))
        self.baudrate_text.setOverwriteMode(True)
        self.connect_button = QPushButton(self.groupBox_3)
        self.connect_button.setObjectName(u"connect_button")
        self.connect_button.setGeometry(QRect(220, 40, 131, 91))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 270, 361, 511))
        self.groupBox_4.setFont(font1)
        self.time = QPlainTextEdit(self.groupBox_4)
        self.time.setObjectName(u"time")
        self.time.setGeometry(QRect(10, 390, 341, 61))
        font8 = QFont()
        font8.setPointSize(25)
        self.time.setFont(font8)
        self.time.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.time.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.date = QPlainTextEdit(self.groupBox_4)
        self.date.setObjectName(u"date")
        self.date.setGeometry(QRect(10, 460, 341, 41))
        self.date.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.date.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tabWidget = QTabWidget(self.groupBox_4)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 361, 371))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.log = QListView(self.tab)
        self.log.setObjectName(u"log")
        self.log.setGeometry(QRect(0, 0, 355, 321))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.position_history_log = QListView(self.tab_2)
        self.position_history_log.setObjectName(u"position_history_log")
        self.position_history_log.setGeometry(QRect(0, 0, 355, 321))
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(940, 280, 531, 321))
        self.groupBox_5.setFont(font1)
        self.init_pos = QPushButton(self.groupBox_5)
        self.init_pos.setObjectName(u"init_pos")
        self.init_pos.setGeometry(QRect(20, 40, 231, 51))
        self.zero_pos = QPushButton(self.groupBox_5)
        self.zero_pos.setObjectName(u"zero_pos")
        self.zero_pos.setGeometry(QRect(270, 40, 231, 51))
        self.save_pos = QPushButton(self.groupBox_5)
        self.save_pos.setObjectName(u"save_pos")
        self.save_pos.setGeometry(QRect(20, 110, 231, 51))
        self.del_pos = QPushButton(self.groupBox_5)
        self.del_pos.setObjectName(u"del_pos")
        self.del_pos.setGeometry(QRect(270, 110, 231, 51))
        self.add_delay_button = QPushButton(self.groupBox_5)
        self.add_delay_button.setObjectName(u"add_delay_button")
        self.add_delay_button.setGeometry(QRect(20, 180, 231, 51))
        self.delay_time = QTextEdit(self.groupBox_5)
        self.delay_time.setObjectName(u"delay_time")
        self.delay_time.setGeometry(QRect(270, 180, 231, 51))
        self.write2eeprom = QPushButton(self.groupBox_5)
        self.write2eeprom.setObjectName(u"write2eeprom")
        self.write2eeprom.setGeometry(QRect(20, 250, 231, 51))
        self.run_program = QPushButton(self.groupBox_5)
        self.run_program.setObjectName(u"run_program")
        self.run_program.setGeometry(QRect(270, 250, 231, 51))
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(940, 630, 531, 151))
        self.groupBox_6.setFont(font1)
        self.speed_in = QPlainTextEdit(self.groupBox_6)
        self.speed_in.setObjectName(u"speed_in")
        self.speed_in.setGeometry(QRect(20, 70, 231, 61))
        font9 = QFont()
        font9.setPointSize(16)
        self.speed_in.setFont(font9)
        self.accel_in = QPlainTextEdit(self.groupBox_6)
        self.accel_in.setObjectName(u"accel_in")
        self.accel_in.setGeometry(QRect(270, 70, 231, 61))
        self.accel_in.setFont(font9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1486, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"SCALA Robot Control", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Forward kinematics", None))
#if QT_CONFIG(accessibility)
        self.progressBar.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.progressBar.setFormat(QCoreApplication.translate("MainWindow", u"%v\u00b0", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"J1", None))
        self.j1_minus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.j1_plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.j2_minus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.j2_plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.progressBar_2.setFormat(QCoreApplication.translate("MainWindow", u"%p\u00b0", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"J2", None))
        self.j3_minus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.j3_plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"J3", None))
        self.progressBar_3.setFormat(QCoreApplication.translate("MainWindow", u"%p\u00b0", None))
        self.progressBar_4.setFormat(QCoreApplication.translate("MainWindow", u"%pmm", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.z_minus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.z_plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Step", None))
        self.step_minus.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.step_plus.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.plainTextEdit_4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Step size", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Inverse kinematics", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.ik_pos_x.setPlainText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Z:", None))
        self.move_position.setText(QCoreApplication.translate("MainWindow", u"Move position", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Connection Panel", None))
        self.com_select.setCurrentText("")
        self.com_select.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Port select", None))
        self.baudrate_text.setDocumentTitle("")
        self.baudrate_text.setPlainText("")
        self.baudrate_text.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Baudrate", None))
        self.connect_button.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.groupBox_4.setTitle("")
        self.time.setPlainText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Log", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Position history", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Programing", None))
        self.init_pos.setText(QCoreApplication.translate("MainWindow", u"Init position", None))
        self.zero_pos.setText(QCoreApplication.translate("MainWindow", u"Zero position", None))
        self.save_pos.setText(QCoreApplication.translate("MainWindow", u"Save position", None))
        self.del_pos.setText(QCoreApplication.translate("MainWindow", u"Delete position", None))
        self.add_delay_button.setText(QCoreApplication.translate("MainWindow", u"Add delay", None))
        self.write2eeprom.setText(QCoreApplication.translate("MainWindow", u"Write to EEPROM", None))
        self.run_program.setText(QCoreApplication.translate("MainWindow", u"Run current program", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Speed | acceleration", None))
        self.speed_in.setPlainText("")
        self.speed_in.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.accel_in.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Acceleration", None))
    # retranslateUi

